export type TransactionType = "INCOME" | "EXPENSE";
export interface Transaction { id:number; description:string; amount:number; date:string; type:TransactionType; note?:string; receiptUrl?:string; co2Kg?:number; isRecurring?:boolean; categoryId:number; categoryName:string; categoryIcon:string; categoryColor:string; bankAccountId?:number; bankAccountName?:string; bankAccountCurrency?:string; bankAccountCurrencySymbol?:string; bankAccountColor?:string; createdAt:string; }
export interface Category { id:number; name:string; icon:string; color:string; type:TransactionType; }
export interface BankAccount { id:number; name:string; icon:string; color:string; currencyCode:string; currencySymbol:string; currencyName:string; country:string; currentBalance:number; isCreditCard:boolean; creditLimit:number; creditUsed:number; createdAt:string; }
export interface Loan { id:number; name:string; loanType:string; totalAmount:number; amountPaid:number; remainingAmount:number; progressPercentage:number; monthlyInstallment?:number; interestRate?:number; startDate?:string; endDate?:string; lender?:string; lenderBankAccountId?:number; lenderBankAccountName?:string; note?:string; active:boolean; createdAt:string; }
export interface AmortizationRow { number:number; date:string; beginningBalance:number; payment:number; principal:number; interest:number; endingBalance:number; }
export interface Budget { id:number; limitAmount:number; month:number; year:number; categoryId:number; categoryName:string; categoryIcon:string; categoryColor:string; spentAmount:number; remainingAmount:number; percentage:number; isOverBudget:boolean; }
export interface SavingsGoal { id:number; name:string; icon:string; color:string; targetAmount:number; currentAmount:number; progressPercentage:number; targetDate?:string; completed:boolean; createdAt:string; }
export interface RecurringTransaction { id:number; name:string; amount:number; type:TransactionType; frequency:"WEEKLY"|"BIWEEKLY"|"MONTHLY"|"QUARTERLY"|"YEARLY"; nextDueDate:string; endDate?:string; lastExecutedDate?:string; active:boolean; note?:string; categoryId:number; categoryName:string; categoryIcon:string; categoryColor:string; bankAccountId?:number; bankAccountName?:string; bankAccountCurrency?:string; createdAt:string; }
export interface DashboardStats { totalIncome:number; totalExpenses:number; balance:number; savingsRate:number; totalCo2Kg:number; healthScore:number; healthGrade:string; topCategories:{name:string;color:string;icon:string;amount:number;percentage:number}[]; monthlyTrend:{month:string;income:number;expense:number}[]; recentTransactions:{id:number;description:string;date:string;categoryName:string;categoryIcon:string;categoryColor:string;type:string;amount:number;currencySymbol:string;co2Kg:number}[]; }
export interface HealthScore { score:number; grade:string; gradeColor:string; summary:string; savingStreak:number; badges:string[]; components:{name:string;icon:string;score:number;maxScore:number;description:string;color:string}[]; }
export interface NetWorth { totalAssets:number; totalLiabilities:number; netWorth:number; history:{month:string;netWorth:number}[]; }
export interface CashFlowForecast { currentBalance:number; projectedMonthlyIncome:number; projectedMonthlyExpense:number; projectedNetSavings:number; daysUntilLow:number; forecastStatus:"HEALTHY"|"WARNING"|"CRITICAL"; dailyForecast:{date:string;projectedBalance:number;eventDescription?:string}[]; }
